### ISSUE TITLE
Problem running Dereplicator on MGF file from MZmine

### ISSUE THREAD

**Issue by lfnothias** [CCMS-UCSD/GNPS_Workflows#67]
The issue was already reported to @alexeigurevich and Hosein, and is caused by the MGF parser, more specifically the 'ION" line in the MGF from MZmine:
`ION=[M+H]+`  
with  "[", "]", and "+" that are special characters. 
The issue is observed both for Dereplicator and Dereplicator+
https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=4093ac6cf5d848ca9f166673b3fb496c
https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=6651b66b49d744788cc3e11640c7566f

The work around for now is to delete these lines in the MGF file.

**Comment by lfnothias** [comment]
I talked to @alexeigurevich and they are working on a new DEREPLICATOR workflow release. 
Note that the issue should occur when running DEREPLICATOR also with the FBMN workflow.

**Comment by mwang87** [comment]
Hey @alexeigurevich did you all get a chance to figure out this issue? 

Let us know!

Ming

**Comment by mwang87** [comment]
Spoke with Hosein, and he said it should have been fixed.

**Comment by lfnothias** [comment]
Please reopen that issue. I cloned the jobs and it still fails to parse the MGF.
@alexeigurevich
Dereplicator+
https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=0dfd26327d9f406e9a6c89a21e774e7f
Dereplicator
https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=6718f172c974411f883748d44084253f

**Comment by mwang87** [comment]
I think for the time being, we can have dereplicator default to not be run in FBMN until we can figure out the issue here.

**Comment by DeepaAcharya** [comment]
Here is a dereplicator job I ran with FBMN and separately both of which failed: https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=bcbb5631c42a49db82fb10aa684988f6

**Comment by alexeigurevich** [comment]
Hi @mwang87 , @lfnothias and @DeepaAcharya !
Thank you for reporting the issue. The actual problem was in Windows-like endings in FBMN-generated MGF files (I mean "\r\n" instead of regular Unix-like "\n"). Unfortunately, a third-party MGF library that we use inside Dereplicator/etc tools was not prepared for this :( It seems that these endings are a relatively new "feature" in the FBMN pipeline because when I tested the pipelines with FBMN files a few months ago, they worked always fine.

Anyway, I fixed the issue and updated both workflows.
I also reran all three mentioned jobs, it seems everything is fine and many PSMs/MSMs are reported.
Louis' Dereplicator+: https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=4132bfbdef12439f9c43fe4f7317c61d
Loius' Dereplicator: 
https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=e9f0759e247842a2b5dabfbe9785c530
Deepa's Dereplicator:
https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=664cc980f31f4365bd0754a19999da10

So, I think the issue could be closed again. Sorry for the inconvenience!

Btw, is there a way to have continuous testing system for the entire FBMN pipeline or just Dereplicator jobs inside to catch such errors in the future automatically? Note that Dereplicator is not fully crashing but it reports the number of files that it fails to process, e.g. see [here](https://gnps.ucsd.edu/ProteoSAFe/result.jsp?task=bcbb5631c42a49db82fb10aa684988f6&view=view_summary). So, it should be relatively easy to check whether the number of failed files is 1 or not.

**Comment by mwang87** [comment]
@alexeigurevich We can totally include dereplicator jobs as part of continuous integration. if you give me links you think are representative, we'll just throw it on and provide a badge for you all. 

We currently use github actions for the continuous integration of running the workflows. Its actually super slick. Also super big thanks! 

Also, throw other jobs our way from your other workflows as well. We currently test 10 or so workflows now with continuous integration testing.

**Comment by alexeigurevich** [comment]
@mwang87 Great! Ok, I will think about the most representative jobs/checks for all our workflows and send you the links tomorrow (in email or separate GitHub issue).

**Comment by lfnothias** [comment]
@mwang87 remember that we will have to reactivate it on the FBMN workflow.

**Comment by lfnothias** [comment]
Hey @mwang87 just a quick reminder that Dereplicator should be readded to FBMN workflow

**Comment by mwang87** [comment]
Its not disabled. It still there on the input.

**Comment by lfnothias** [comment]
@alexeigurevich, the same issue might be happening in DEREPLICATOR PLUS:
https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=71970b5049ed494a937c8578225b3e7c
The same MGF file works for DEREPLICATOR https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=1fafd4d4fe7e47dd9dd0b3d8bb0e6606
